export interface CommandSurfaceEntry {
  command: string;
  toolName: string;
  handlerSymbol: string;
  mutatesRuntime: boolean;
}

export type ToolHandlerBinding = readonly [toolName: string, handlerSymbol: string];

export const COMMAND_SURFACE = [
  { command: "doctor", toolName: "doctor", handlerSymbol: "doctor", mutatesRuntime: false },
  { command: "project-info", toolName: "project_info", handlerSymbol: "projectInfo", mutatesRuntime: false },
  { command: "routes", toolName: "expo_router_sitemap", handlerSymbol: "expoRouterSitemap", mutatesRuntime: false },
  { command: "devices", toolName: "list_devices", handlerSymbol: "listDevices", mutatesRuntime: false },
  { command: "session", toolName: "session", handlerSymbol: "sessionCommand", mutatesRuntime: false },
  { command: "target", toolName: "target", handlerSymbol: "targetCommand", mutatesRuntime: false },
  { command: "snapshot", toolName: "snapshot", handlerSymbol: "snapshotCommand", mutatesRuntime: false },
  { command: "refs", toolName: "refs", handlerSymbol: "refsCommand", mutatesRuntime: false },
  { command: "get", toolName: "get_ref", handlerSymbol: "getRefCommand", mutatesRuntime: false },
  { command: "find", toolName: "find", handlerSymbol: "findCommand", mutatesRuntime: false },
  { command: "wait", toolName: "wait", handlerSymbol: "waitCommand", mutatesRuntime: false },
  { command: "batch", toolName: "batch", handlerSymbol: "batchCommand", mutatesRuntime: false },
  { command: "boot-simulator", toolName: "boot_simulator", handlerSymbol: "bootSimulator", mutatesRuntime: true },
  { command: "open-url", toolName: "open_url", handlerSymbol: "openUrl", mutatesRuntime: true },
  { command: "launch-app", toolName: "launch_app", handlerSymbol: "launchApp", mutatesRuntime: true },
  { command: "terminate-app", toolName: "terminate_app", handlerSymbol: "terminateApp", mutatesRuntime: true },
  { command: "reload-app", toolName: "reload_app", handlerSymbol: "reloadApp", mutatesRuntime: true },
  { command: "open-dev-menu", toolName: "runtime_inspector", handlerSymbol: "runtimeInspector", mutatesRuntime: true },
  { command: "install-app", toolName: "install_app", handlerSymbol: "installApp", mutatesRuntime: true },
  { command: "uninstall-app", toolName: "uninstall_app", handlerSymbol: "uninstallApp", mutatesRuntime: true },
  { command: "long-press", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "dbltap", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "fill", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "type", toolName: "keyboard", handlerSymbol: "keyboardCommand", mutatesRuntime: true },
  { command: "press", toolName: "keyboard", handlerSymbol: "keyboardCommand", mutatesRuntime: true },
  { command: "focus", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "blur", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "select", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "check", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "uncheck", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "drag", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "scroll", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "scroll-into-view", toolName: "ref_action", handlerSymbol: "refActionCommand", mutatesRuntime: true },
  { command: "clipboard", toolName: "clipboard", handlerSymbol: "clipboardCommand", mutatesRuntime: true },
  { command: "keyboard", toolName: "keyboard", handlerSymbol: "keyboardCommand", mutatesRuntime: true },
  { command: "set", toolName: "set_environment", handlerSymbol: "setEnvironmentCommand", mutatesRuntime: true },
  { command: "logs", toolName: "collect_app_logs", handlerSymbol: "collectAppLogs", mutatesRuntime: false },
  { command: "screenshot", toolName: "automation_take_screenshot", handlerSymbol: "automationTakeScreenshot", mutatesRuntime: false },
  { command: "tap", toolName: "automation_tap", handlerSymbol: "automationTap", mutatesRuntime: true },
  { command: "gesture", toolName: "automation_gesture", handlerSymbol: "automationGesture", mutatesRuntime: true },
  { command: "open-route", toolName: "open_expo_route", handlerSymbol: "openExpoRoute", mutatesRuntime: true },
  { command: "ux-context", toolName: "capture_ux_context", handlerSymbol: "captureUxContext", mutatesRuntime: false },
  { command: "annotate-screen", toolName: "annotate_screen", handlerSymbol: "annotateScreen", mutatesRuntime: false },
  { command: "inspector", toolName: "runtime_inspector", handlerSymbol: "runtimeInspector", mutatesRuntime: false },
  { command: "review-overlay", toolName: "review_overlay", handlerSymbol: "reviewOverlay", mutatesRuntime: false },
  { command: "review-overlay-server", toolName: "review_overlay", handlerSymbol: "reviewOverlay", mutatesRuntime: false },
  { command: "review-next", toolName: "review_next_step", handlerSymbol: "reviewNextStep", mutatesRuntime: false },
  { command: "annotation-server", toolName: "annotation_server", handlerSymbol: "removedAnnotationServerCommand", mutatesRuntime: false },
  { command: "devtools", toolName: "devtools", handlerSymbol: "devtoolsCommand", mutatesRuntime: false },
  { command: "console", toolName: "console", handlerSymbol: "consoleCommand", mutatesRuntime: false },
  { command: "errors", toolName: "errors", handlerSymbol: "errorsCommand", mutatesRuntime: false },
  { command: "metro", toolName: "metro", handlerSymbol: "metroCommand", mutatesRuntime: false },
  { command: "profiler", toolName: "perf", handlerSymbol: "perfCommand", mutatesRuntime: false },
  { command: "navigation", toolName: "navigation", handlerSymbol: "navigationCommand", mutatesRuntime: true },
  { command: "network", toolName: "network", handlerSymbol: "networkCommand", mutatesRuntime: false },
  { command: "storage", toolName: "storage", handlerSymbol: "storageCommand", mutatesRuntime: true },
  { command: "state", toolName: "state", handlerSymbol: "stateCommand", mutatesRuntime: true },
  { command: "controls", toolName: "controls", handlerSymbol: "controlsCommand", mutatesRuntime: true },
  { command: "bridge", toolName: "bridge", handlerSymbol: "bridgeCommand", mutatesRuntime: false },
  { command: "accessibility", toolName: "accessibility", handlerSymbol: "accessibilityCommand", mutatesRuntime: false },
  { command: "dialog", toolName: "dialog", handlerSymbol: "dialogCommand", mutatesRuntime: true },
  { command: "sheet", toolName: "sheet", handlerSymbol: "sheetCommand", mutatesRuntime: true },
  { command: "record", toolName: "record", handlerSymbol: "recordCommand", mutatesRuntime: false },
  { command: "diff", toolName: "diff", handlerSymbol: "diffCommand", mutatesRuntime: false },
  { command: "inspect", toolName: "debug_inspect", handlerSymbol: "debugInspectCommand", mutatesRuntime: false },
  { command: "highlight", toolName: "highlight", handlerSymbol: "highlightCommand", mutatesRuntime: false },
  { command: "expo", toolName: "expo", handlerSymbol: "expoCommand", mutatesRuntime: false },
  { command: "rn", toolName: "rn", handlerSymbol: "rnCommand", mutatesRuntime: false },
  { command: "perf", toolName: "perf", handlerSymbol: "perfCommand", mutatesRuntime: false },
  { command: "dashboard", toolName: "dashboard", handlerSymbol: "dashboardCommand", mutatesRuntime: false },
  { command: "review", toolName: "review", handlerSymbol: "reviewCommand", mutatesRuntime: false },
  { command: "policy", toolName: "policy", handlerSymbol: "policyCommand", mutatesRuntime: false },
  { command: "redact", toolName: "redact", handlerSymbol: "redactCommand", mutatesRuntime: false },
  { command: "skills", toolName: "skills", handlerSymbol: "skillsCommand", mutatesRuntime: false },
  { command: "install", toolName: "install", handlerSymbol: "installCommand", mutatesRuntime: false },
  { command: "upgrade", toolName: "upgrade", handlerSymbol: "upgradeCommand", mutatesRuntime: false },
  { command: "release", toolName: "release", handlerSymbol: "releaseCommand", mutatesRuntime: false },
  { command: "live-backlog", toolName: "live_backlog", handlerSymbol: "liveBacklogCommand", mutatesRuntime: false },
  { command: "trace", toolName: "trace_interaction", handlerSymbol: "traceInteraction", mutatesRuntime: false },
] as const satisfies readonly CommandSurfaceEntry[];

export const COMMAND_ALIASES: Readonly<Record<string, string>> = Object.freeze(Object.fromEntries(
  COMMAND_SURFACE.map((entry) => [entry.command, entry.toolName]),
));

export const TOOL_HANDLER_BINDINGS = COMMAND_SURFACE
  .filter((entry, index, entries) => entries.findIndex((candidate) => candidate.toolName === entry.toolName) === index)
  .map((entry) => [entry.toolName, entry.handlerSymbol] as const) satisfies readonly ToolHandlerBinding[];

export function commandAliases(): Record<string, string> {
  return { ...COMMAND_ALIASES };
}

export function commandNames(): string[] {
  return COMMAND_SURFACE.map((entry) => entry.command);
}

export function manipulatingCommandNames(): string[] {
  return COMMAND_SURFACE.filter((entry) => entry.mutatesRuntime).map((entry) => entry.command);
}

export const GLOBAL_FLAGS = [
  "--json                 Write { ok, data } JSON to stdout",
  "--plain                Write stable line-oriented output to stdout",
  "--quiet                Suppress non-essential human output",
  "--version              Print CLI version",
  "--root <dir>           Default project root for commands that accept --cwd",
  "--state-dir <dir>      Persist a run record JSON file in this directory",
  "--action-policy <path> Permit gated write/device actions from a JSON policy",
  "--max-output <chars>   Truncate stdout payloads after this many characters",
  "--content-boundaries   Wrap stdout data in an explicit untrusted-output boundary",
  "--allow-runtime-eval <true|false>",
  "                       Permit gated Hermes Runtime.evaluate predicates",
  "--confirm-actions <list>",
  "                       Reserved for interactive confirmations; noninteractive runs deny",
  "--record               Persist a run record under <root>/.scratch/expo98/runs",
  "--debug                Include debug fields in machine-readable errors",
  "--no-color             Disable color; output is uncolored by default",
  "--no-input             Reserved for noninteractive safety; this CLI never prompts",
] as const;

export const DISCOVERY_COMMANDS = [
  "doctor                 Check local tool availability and project context",
  "project-info           Inspect Expo dependencies and app config",
  "routes                 List Expo Router routes",
  "devices                List iOS simulators and Android devices",
  "session new [name]     Create an evidence session and artifact namespace",
  "target list            List stable simulator/app/Metro target handles",
  "target select <id>     Store the active target on the latest session",
  "target current         Show the selected target for the latest session",
  "snapshot               Capture semantic UI refs for the selected target",
  "refs                   List cached refs from the latest snapshot",
  "get <field> <ref>      Inspect one cached ref field",
  "find <kind> <value>     Locate cached semantic refs and optionally plan an action",
  "wait                   Wait for cached text or ref state evidence",
  "batch                  Run multiple expo98 command steps in one process",
] as const;

export const SIMULATOR_AND_APP_COMMANDS = [
  "boot-simulator         Boot an iOS simulator",
  "open-url <url>         Open a URL/deep link",
  "launch-app             Launch an installed app",
  "terminate-app          Terminate an installed app",
  "reload-app             Relaunch an app as a practical JS reload fallback",
  "open-dev-menu          Open the React Native dev menu on the simulator",
  "install-app            Install an .app/.ipa with an action policy",
  "uninstall-app          Uninstall an app with an action policy",
  "open-route [route]     Open an Expo Router route",
  "screenshot             Capture a simulator/device screenshot",
  "tap                    Tap device coordinates",
  "fill/press/type        Act on focused input or cached semantic refs",
  "long-press/dbltap      Run semantic ref gestures from cached bounds",
  "scroll/drag            Run semantic ref or coordinate gestures",
  "clipboard              Read, write, or paste simulator clipboard text",
  "keyboard               Type text or press a key through local tooling",
  "set                    Mutate explicit simulator environment settings",
  "gesture                Run tap, long-press, drag, or swipe gesture evidence",
] as const;

export const EVIDENCE_AND_RUNTIME_COMMANDS = [
  "logs                   Collect recent app/device logs",
  "ux-context             Capture screenshot, route, runtime, hierarchy, and log context",
  "annotate-screen        Prepare/read an in-app annotation overlay",
  "inspector              Toggle RN inspector and install/read simulator comments",
  "review-overlay         Scaffold/run an in-app Codex review overlay",
  "review-next            Suggest the next constraint-focused UI review step",
  "devtools capabilities  Report structured DevTools capability records",
  "console                Read bounded JS console diagnostics",
  "errors                 Read bounded JS error diagnostics",
  "metro status           Report Metro status, targets, and symbolication",
  "navigation             Read or drive app navigation bridge state",
  "network                Read metadata-only app network evidence, waterfall, and redacted HAR",
  "storage                Read or mutate app storage through policy gates",
  "state                  List/save/load/clear app state snapshots",
  "controls               List, inspect, or press app-defined controls",
  "bridge                 Plan/check dev-only app bridge install, health, and domains",
  "accessibility          Capture native accessibility tree/audit evidence",
  "dialog                 Report or act on visible dialog blockers",
  "sheet                  Report or dismiss visible sheet/modal blockers",
  "record                 Create recording evidence artifacts",
  "diff                   Write snapshot or screenshot diff artifacts",
  "expo                   Inspect Expo modules, config, doctor, upstream policy, and prebuild risk",
  "rn                     Inspect React Native tree, refs, renders, and fiber evidence",
  "perf                   Measure summary, interaction, report, frame, native, and bundle evidence",
  "dashboard              Start, stop, or report local session observability",
  "skills                 List or print bundled companion skill guidance",
  "install                Check local install target paths",
  "upgrade                Check local upgrade status",
  "release                Run local release packaging checks",
  "live-backlog           Generate or run the source-derived live backlog",
  "trace                  Start/read/stop/clear a Hermes interaction trace",
  "profiler start|stop    Native profiler evidence boundary alias for perf ettrace",
  "inspect <ref>          Inspect cached source/props/bounds plus Metro target status",
  "highlight <ref>        Write a bounded highlight evidence overlay",
  "review report|matrix   Assemble captured evidence into review artifacts",
  "policy show|check      Explain or evaluate action-policy decisions",
  "redact <file>          Redact secrets from a JSON/text file",
] as const;

export const EXAMPLES = [
  "expo98 --json doctor",
  "expo98 --json session new review",
  "expo98 --json target list",
  "expo98 --json snapshot --interactive --source --bounds",
  "expo98 --json get source @e1",
  "expo98 --json find role button --name Add tap",
  "expo98 --json wait --text Customers",
  "expo98 --json wait @e1 --state visible",
  "expo98 --json batch '[\"wait\",\"--text\",\"Customers\"]' '[\"get\",\"source\",\"@e1\"]' --bail true",
  "expo98 --json screenshot --annotate",
  "expo98 --json open-route /customers --cwd apps/mobile --scheme myapp --action-policy expo98.policy.json",
  "expo98 --json annotate-screen prepare --cwd apps/mobile --serve true",
  "expo98 --json inspector probe --metro-port 8081",
  "expo98 --json inspector install-comment-menu --metro-port 8081",
  "expo98 --json inspector open-dev-menu",
  "expo98 --json terminate-app --bundle-id com.example.app",
  "expo98 --json reload-app --bundle-id com.example.app",
  "expo98 --json fill @e1 \"hello\"",
  "expo98 --json clipboard read",
  "expo98 --json set appearance dark --action-policy expo98.policy.json",
  "expo98 --json review-overlay scaffold --cwd apps/mobile",
  "expo98 --json review-overlay prepare --cwd apps/mobile --serve true",
  "expo98 --json review-next --surface calendar --stage pre-patch --issue \"drag creates scroll conflict\"",
  "expo98 --json devtools capabilities --metro-port 8081",
  "expo98 --json expo upstream-policy --cwd apps/mobile",
  "expo98 --json console --limit 50 --metro-port 8081",
  "expo98 --json errors --limit 50 --metro-port 8081",
  "expo98 --json metro status --metro-port 8081",
  "expo98 --json navigation state --metro-port 8081",
  "expo98 --json navigation deep-link /customers --scheme myapp",
  "expo98 --json network requests --metro-port 8081",
  "expo98 --json network waterfall --metro-port 8081",
  "expo98 --json network har stop network.har --metro-port 8081",
  "expo98 --json storage async list --metro-port 8081",
  "expo98 --json controls list --metro-port 8081",
  "expo98 --json bridge plan --cwd apps/mobile",
  "expo98 --json bridge health --cwd apps/mobile --metro-port 8081",
  "expo98 --json bridge domains storage set --cwd apps/mobile --metro-port 8081",
  "expo98 --json accessibility tree",
  "expo98 --json dialog status --metro-port 8081",
  "expo98 --json diff snapshot --baseline before.json",
  "expo98 --json expo modules --cwd apps/mobile",
  "expo98 --json rn tree --metro-port 8081",
  "expo98 --json rn renders read --metro-port 8081",
  "expo98 --json rn inspect @e1",
  "expo98 --json perf summary --metro-port 8081",
  "expo98 --json perf interaction start \"tab-customers\" --metro-port 8081",
  "expo98 --json perf interaction stop \"tab-customers\" --metro-port 8081",
  "expo98 --json perf report \"tab-customers\" --metro-port 8081 --native-artifact sample.txt",
  "expo98 --json perf action \"open customer\" --metro-port 8081",
  "expo98 --json perf bundle dist/index.ios.bundle",
  "expo98 --json perf compare --baseline before.json --candidate after.json",
  "expo98 --json perf budget check --file expo98.perf.json --candidate after.json",
  "expo98 --json perf memgraph capture heap.memgraph",
  "expo98 --json profiler start",
  "expo98 --json inspect @e1",
  "expo98 --json policy check action uninstall-app --action-policy expo98.policy.json",
  "expo98 --json redact run-record.json --output-path run-record.redacted.json",
  "expo98 --json dashboard start",
  "expo98 --json skills get expo98-cli",
  "expo98 --json release check",
  "expo98 --json gesture long-press --x 160 --y 720 --duration-ms 900 --dry-run true",
  "expo98 --json live-backlog matrix --cwd apps/mobile",
  "expo98 --json trace --action read --metro-port 8081",
] as const;
