/**
 * `bridge-files` — the generated in-app bridge artifacts + their on-disk layout.
 *
 * Two files make up an installed bridge:
 *   - `.expo98/bridge.json` — `BridgeMetadata` (schema 1, version 1.0.0, dev-only).
 *   - `src/expo98-devtools-bridge.ts` — the generated registration source.
 *
 * Legacy installs used `.expo-ios/bridge.json` — kept as a read/remove fallback
 * so `remove` cleans up an older install.
 *
 * `// SEAM (Expo SDK)`: the REAL in-app delivery of this bridge to a running app
 * is the official Expo DevTools Plugins SDK path (brief Q#10). This package only
 * writes the project-side source; the SDK wires it into the dev client. The
 * generated source is dev-only (AC-009) and registers under a single global.
 */
import { BRIDGE_VERSION, type BridgeDomain, type BridgeMetadata, SCHEMA_VERSION } from "@expo98/domain"

/** `EXPO98_BRIDGE_VERSION` (AC-008/027) — the version stamped into metadata. */
export const EXPO98_BRIDGE_VERSION = BRIDGE_VERSION // "1.0.0"

/** The bridge schema version stamped into metadata (AC-008/027). */
export const BRIDGE_SCHEMA_VERSION = SCHEMA_VERSION // 1

/** The domains the generated bridge advertises (AC-008/027). */
export const BRIDGE_DOMAINS: ReadonlyArray<BridgeDomain> = [
  "navigation",
  "network",
  "storage",
  "controls",
  "performance",
  "snapshot",
]

/** Canonical metadata object the installer writes. */
export const bridgeMetadata = (): BridgeMetadata => ({
  schemaVersion: BRIDGE_SCHEMA_VERSION,
  bridgeVersion: EXPO98_BRIDGE_VERSION,
  developmentOnly: true,
  generatedBy: "run-expo",
  domains: BRIDGE_DOMAINS,
})

/** On-disk layout, relative to a project root. */
export interface BridgeFilePaths {
  /** `<root>/.expo98/bridge.json`. */
  readonly metadata: string
  /** `<root>/src/expo98-devtools-bridge.ts`. */
  readonly source: string
  /** Legacy `<root>/.expo-ios/bridge.json` (read/remove fallback). */
  readonly legacyMetadata: string
}

const joinPath = (root: string, rel: string): string => `${root.replace(/\/+$/, "")}/${rel}`

export const bridgeFilePaths = (root: string): BridgeFilePaths => ({
  metadata: joinPath(root, ".expo98/bridge.json"),
  source: joinPath(root, "src/expo98-devtools-bridge.ts"),
  legacyMetadata: joinPath(root, ".expo-ios/bridge.json"),
})

/** The metadata file contents (pretty JSON). */
export const bridgeMetadataContents = (): string => JSON.stringify(bridgeMetadata(), null, 2) + "\n"

/**
 * The generated registration source (AC-009 dev-only). It refuses to register
 * unless `__DEV__` is a defined truthy value and exposes exactly one global,
 * `globalThis.__EXPO98_DEVTOOLS_BRIDGE__`, via `registerExpo98DevtoolsBridge`
 * (the ONLY registration path — SME-confirmed, AC-009).
 */
export const bridgeSourceContents = (): string => `/**
 * GENERATED by @expo98/expo-integration — DO NOT EDIT.
 * In-app devtools bridge (DEVELOPMENT ONLY). schema ${BRIDGE_SCHEMA_VERSION}, version ${EXPO98_BRIDGE_VERSION}.
 */
export const EXPO98_BRIDGE_VERSION = ${JSON.stringify(EXPO98_BRIDGE_VERSION)} as const

export type Expo98BridgeRegistration = {
  readonly version: string
  readonly schemaVersion: number
  readonly domains: ReadonlyArray<string>
}

type Expo98Global = typeof globalThis & { readonly __DEV__?: boolean }

declare global {
  var __EXPO98_DEVTOOLS_BRIDGE__: Expo98BridgeRegistration | undefined
}

/**
 * The ONLY registration path (AC-009). Refuses outside development:
 *   - typeof __DEV__ === "undefined" → "development-mode-required"
 *   - __DEV__ === false              → "production-build"
 *   - otherwise registers globalThis.__EXPO98_DEVTOOLS_BRIDGE__
 */
export function registerExpo98DevtoolsBridge():
  | { ok: true; registration: Expo98BridgeRegistration }
  | { ok: false; reason: "development-mode-required" | "production-build" } {
  const dev = (globalThis as Expo98Global).__DEV__
  if (typeof dev === "undefined") {
    return { ok: false, reason: "development-mode-required" }
  }
  if (dev === false) {
    return { ok: false, reason: "production-build" }
  }
  const registration: Expo98BridgeRegistration = {
    version: EXPO98_BRIDGE_VERSION,
    schemaVersion: ${BRIDGE_SCHEMA_VERSION},
    domains: ${JSON.stringify(BRIDGE_DOMAINS)}
  }
  globalThis.__EXPO98_DEVTOOLS_BRIDGE__ = registration
  return { ok: true, registration }
}
`
