import { bridgeMetadata } from "./domain.js";

export function buildBridgeSource() {
  return `// Generated by expo-ios. Import this file only from development-only app code guarded by __DEV__.
export const expoIosDevtoolsBridgeMetadata = ${JSON.stringify(bridgeMetadata(), null, 2)} as const;

export function registerExpoIosDevtoolsBridge() {
  if (typeof __DEV__ === "undefined") return { registered: false, reason: "development-mode-required" };
  if (!__DEV__) return { registered: false, reason: "production-build" };
  const bridge = {
    registered: true,
    metadata: expoIosDevtoolsBridgeMetadata,
    bridgeVersion: expoIosDevtoolsBridgeMetadata.bridgeVersion,
    domains: expoIosDevtoolsBridgeMetadata.domains.map((name) => ({ name })),
  };
  globalThis.__EXPO_IOS_DEVTOOLS_BRIDGE__ = bridge;
  return { registered: true, metadata: expoIosDevtoolsBridgeMetadata };
}
`;
}

/**
 * RULE-006: transformed registration hardening. Legacy allowed undefined
 * __DEV__; the modernization decision is to fail closed unless dev is explicit.
 */
export function shouldRegisterBridge({ dev }: { dev?: boolean } = {}) {
  if (dev === true) {
    return { registered: true };
  }
  if (dev === false) {
    return { registered: false, reason: "production-build" };
  }
  return { registered: false, reason: "development-mode-required" };
}
