export const COMMAND_ARG_NAMES = [
  "install",
  "upgrade",
  "doctor",
  "project-info",
  "routes",
  "devices",
  "boot-simulator",
  "open-url",
  "open-route",
  "launch-app",
  "terminate-app",
  "reload-app",
  "open-dev-menu",
  "install-app",
  "uninstall-app",
  "screenshot",
  "tap",
  "long-press",
  "dbltap",
  "fill",
  "type",
  "focus",
  "blur",
  "press",
  "keyboard",
  "select",
  "check",
  "uncheck",
  "scroll",
  "scroll-into-view",
  "drag",
  "gesture",
  "logs",
  "ux-context",
  "inspector",
  "trace",
  "annotate-screen",
  "review-overlay",
  "review-next",
  "review",
  "session",
  "target",
  "snapshot",
  "refs",
  "get",
  "find",
  "wait",
  "batch",
  "devtools",
  "console",
  "errors",
  "metro",
  "perf",
  "skills",
  "clipboard",
  "set",
  "network",
  "navigation",
  "storage",
  "state",
  "controls",
  "bridge",
  "rn",
  "expo",
  "diff",
  "record",
  "accessibility",
  "dialog",
  "sheet",
  "profiler",
  "inspect",
  "highlight",
  "instrumentation",
  "dashboard",
  "policy",
  "redact",
] as const;

export const POSITIONAL_REF_ACTION_COMMANDS = [
  "long-press",
  "dbltap",
  "fill",
  "type",
  "focus",
  "blur",
  "press",
  "keyboard",
  "select",
  "check",
  "uncheck",
  "scroll",
  "scroll-into-view",
  "drag",
] as const;

export const REF_FIELDS = ["text", "props", "box", "style", "source"] as const;
export const FIND_KINDS = [
  "role",
  "text",
  "label",
  "placeholder",
  "testid",
  "source",
  "first",
  "last",
  "nth",
] as const;

export const REVIEW_NEXT_SURFACES = [
  "calendar",
  "timeline",
  "form",
  "list",
  "navigation",
  "editor",
  "generic",
] as const;

export const REVIEW_NEXT_STAGES = [
  "intake",
  "pre-patch",
  "post-patch",
  "verifier-failed",
  "interaction",
  "handoff",
] as const;

export const ENVIRONMENT_CATEGORIES = [
  "appearance",
  "content-size",
  "locale",
  "timezone",
  "location",
  "network",
  "permissions",
  "orientation",
  "keyboard",
] as const;

export const ACTIONS_BY_ARG_DOMAIN = {
  appLifecycle: ["terminate", "reload", "open-dev-menu", "install", "uninstall"],
  gesture: ["tap", "long-press", "tap-and-hold", "drag", "swipe"],
  inspector: ["probe", "toggle", "install-comment-menu", "read-comments", "clear-comments", "open-dev-menu"],
  trace: ["start", "read", "stop", "clear"],
  reviewOverlay: ["prepare", "scaffold", "server", "read", "clear"],
  review: ["report", "matrix"],
  session: ["list", "show", "new", "close", "clean"],
  target: ["list", "select", "current"],
  refAction: [
    "tap",
    "long-press",
    "focus",
    "scroll-into-view",
    "dbltap",
    "blur",
    "check",
    "uncheck",
    "fill",
    "type",
    "select",
    "drag",
    "press",
    "keyboard",
    "scroll",
  ],
  wait: ["time", "ref", "text", "route", "metro-ready", "app-ready", "fn"],
  devtools: ["status", "open", "panels", "capabilities", "events"],
  devtoolsEvents: ["start", "read", "stop"],
  perf: [
    "summary",
    "startup",
    "action",
    "bundle",
    "mark-list",
    "mark-clear",
    "measure-start",
    "measure-stop",
    "compare",
    "budget-check",
    "startup-modules",
    "js-thread",
    "frames",
    "memory",
    "ettrace-start",
    "ettrace-stop",
    "memgraph-capture",
  ],
  skills: ["list", "get"],
  clipboard: ["read", "paste", "write"],
  network: ["status", "clear", "requests", "request", "har-start", "har-stop"],
  navigation: ["state", "back", "pop-to-root", "tab", "deep-link"],
  storage: ["list", "get", "set", "clear", "trace"],
  state: ["save", "load", "list", "clear"],
  controls: ["list", "get", "press", "set"],
  bridge: ["status", "plan", "health", "domains", "install", "remove"],
  rn: ["tree", "inspect", "renders-start", "renders-stop", "fiber"],
  expo: ["modules", "config", "doctor", "upstream-policy", "prebuild-plan"],
  diff: ["snapshot", "screenshot", "route"],
  record: ["start", "stop", "status"],
  accessibility: ["tree", "audit", "inspect", "focus"],
  dialog: ["status", "dismiss", "accept"],
  sheet: ["status", "dismiss"],
  dashboard: ["start", "stop", "status"],
  profiler: ["start", "stop"],
  instrumentation: ["status", "manifest", "install", "remove", "call"],
  policy: ["show", "check", "redact"],
} as const;

export type CommandArgName = (typeof COMMAND_ARG_NAMES)[number];

export type CommandArgContract = {
  command: CommandArgName;
  argType: string;
  actions: string[];
};

export const COMMAND_ARG_CONTRACTS = [
  contract("install", "InstallArgs"),
  contract("upgrade", "UpgradeArgs"),
  contract("doctor", "DoctorArgs"),
  contract("project-info", "ProjectInfoArgs"),
  contract("routes", "RoutesArgs"),
  contract("devices", "DevicesArgs"),
  contract("boot-simulator", "BootSimulatorArgs"),
  contract("open-url", "OpenUrlArgs"),
  contract("open-route", "OpenRouteArgs"),
  contract("launch-app", "LaunchAppArgs"),
  contract("terminate-app", "AppLifecycleArgs", ACTIONS_BY_ARG_DOMAIN.appLifecycle),
  contract("reload-app", "AppLifecycleArgs", ACTIONS_BY_ARG_DOMAIN.appLifecycle),
  contract("open-dev-menu", "AppLifecycleArgs", ACTIONS_BY_ARG_DOMAIN.appLifecycle),
  contract("install-app", "AppLifecycleArgs", ACTIONS_BY_ARG_DOMAIN.appLifecycle),
  contract("uninstall-app", "AppLifecycleArgs", ACTIONS_BY_ARG_DOMAIN.appLifecycle),
  contract("screenshot", "ScreenshotArgs"),
  contract("tap", "TapArgs"),
  ...POSITIONAL_REF_ACTION_COMMANDS.map((command) => contract(command, "RefActionArgs", ACTIONS_BY_ARG_DOMAIN.refAction)),
  contract("gesture", "GestureArgs", ACTIONS_BY_ARG_DOMAIN.gesture),
  contract("logs", "LogsArgs"),
  contract("ux-context", "UxContextArgs"),
  contract("inspector", "InspectorArgs", ACTIONS_BY_ARG_DOMAIN.inspector),
  contract("trace", "TraceArgs", ACTIONS_BY_ARG_DOMAIN.trace),
  contract("annotate-screen", "AnnotateScreenArgs"),
  contract("review-overlay", "ReviewOverlayArgs", ACTIONS_BY_ARG_DOMAIN.reviewOverlay),
  contract("review-next", "ReviewNextArgs"),
  contract("review", "ReviewArgs", ACTIONS_BY_ARG_DOMAIN.review),
  contract("session", "SessionArgs", ACTIONS_BY_ARG_DOMAIN.session),
  contract("target", "TargetArgs", ACTIONS_BY_ARG_DOMAIN.target),
  contract("snapshot", "SnapshotArgs"),
  contract("refs", "RefsArgs"),
  contract("get", "RefGetArgs"),
  contract("find", "FindArgs"),
  contract("wait", "WaitArgs", ACTIONS_BY_ARG_DOMAIN.wait),
  contract("batch", "BatchArgs"),
  contract("devtools", "DevToolsArgs", ACTIONS_BY_ARG_DOMAIN.devtools),
  contract("console", "ConsoleArgs"),
  contract("errors", "ErrorsArgs"),
  contract("metro", "MetroArgs", ["status", "reload", "symbolicate"]),
  contract("perf", "PerfArgs", ACTIONS_BY_ARG_DOMAIN.perf),
  contract("skills", "SkillsArgs", ACTIONS_BY_ARG_DOMAIN.skills),
  contract("clipboard", "ClipboardArgs", ACTIONS_BY_ARG_DOMAIN.clipboard),
  contract("set", "EnvironmentSetArgs"),
  contract("network", "NetworkArgs", ACTIONS_BY_ARG_DOMAIN.network),
  contract("navigation", "NavigationArgs", ACTIONS_BY_ARG_DOMAIN.navigation),
  contract("storage", "StorageArgs", ACTIONS_BY_ARG_DOMAIN.storage),
  contract("state", "StateArgs", ACTIONS_BY_ARG_DOMAIN.state),
  contract("controls", "ControlsArgs", ACTIONS_BY_ARG_DOMAIN.controls),
  contract("bridge", "BridgeArgs", ACTIONS_BY_ARG_DOMAIN.bridge),
  contract("rn", "RnArgs", ACTIONS_BY_ARG_DOMAIN.rn),
  contract("expo", "ExpoArgs", ACTIONS_BY_ARG_DOMAIN.expo),
  contract("diff", "DiffArgs", ACTIONS_BY_ARG_DOMAIN.diff),
  contract("record", "RecordArgs", ACTIONS_BY_ARG_DOMAIN.record),
  contract("accessibility", "AccessibilityArgs", ACTIONS_BY_ARG_DOMAIN.accessibility),
  contract("dialog", "DialogArgs", ACTIONS_BY_ARG_DOMAIN.dialog),
  contract("sheet", "SheetArgs", ACTIONS_BY_ARG_DOMAIN.sheet),
  contract("profiler", "ProfilerArgs", ACTIONS_BY_ARG_DOMAIN.profiler),
  contract("inspect", "InspectArgs"),
  contract("highlight", "HighlightArgs"),
  contract("instrumentation", "InstrumentationArgs", ACTIONS_BY_ARG_DOMAIN.instrumentation),
  contract("dashboard", "DashboardArgs", ACTIONS_BY_ARG_DOMAIN.dashboard),
  contract("policy", "PolicyArgs", ACTIONS_BY_ARG_DOMAIN.policy),
  contract("redact", "PolicyArgs", ["redact"]),
] as const satisfies readonly CommandArgContract[];

export function listCommandArgContracts(): CommandArgContract[] {
  return COMMAND_ARG_CONTRACTS.map((item) => ({
    command: item.command,
    argType: item.argType,
    actions: [...item.actions],
  }));
}

export function getCommandArgContract(command: string): CommandArgContract | null {
  const contract = COMMAND_ARG_CONTRACTS.find((item) => item.command === command);
  if (contract === undefined) {
    return null;
  }
  return {
    command: contract.command,
    argType: contract.argType,
    actions: [...contract.actions],
  };
}

export function commandSupportsAction(command: string, action: string): boolean {
  return getCommandArgContract(command)?.actions.includes(action) ?? false;
}

function contract(
  command: CommandArgName,
  argType: string,
  actions: readonly string[] = [],
): CommandArgContract {
  return {
    command,
    argType,
    actions: [...actions],
  };
}
